_wandb:
    value:
        cli_version: 0.22.1
        e:
            mhy6u6cgxsz9hpmrqck3sx46zc7d90m4:
                args:
                    - --size
                    - "10"
                    - --speed
                    - "1"
                    - --n_epochs
                    - "400"
                    - --num_envs
                    - "1"
                    - --val_batch_episodes
                    - "4"
                    - --vectorhash
                    - --input_type
                    - g_idx
                    - --use_wandb
                    - --batch_episodes
                    - "128"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 96
                cpu_count_logical: 192
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "1993782456320"
                        used: "460014759936"
                email: jack.g.king@gmail.com
                executable: /om2/user/jackking/conda/envs/cls/bin/python
                gpu: NVIDIA A100 80GB PCIe
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-1131a825-9a79-de12-c9e4-67f5cc3405a2
                host: node107
                memory:
                    total: "1081747828736"
                os: Linux-4.18.0-372.9.1.el8.x86_64-x86_64-with-glibc2.28
                program: /rdma/vast-rdma/vast/fiete/jackking/cls/train.py
                python: CPython 3.12.11
                root: /rdma/vast-rdma/vast/fiete/jackking/cls
                slurm:
                    cluster_name: openmind7
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "2"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: evlab
                    job_cpus_per_node: "2"
                    job_gid: "102035"
                    job_gpus: "6"
                    job_id: "43902485"
                    job_name: cls
                    job_nodelist: node107
                    job_num_nodes: "1"
                    job_partition: normal
                    job_qos: normal
                    job_uid: "192617"
                    job_user: jackking
                    jobid: "43902485"
                    localid: "0"
                    mem_per_node: "51200"
                    nnodes: "1"
                    node_aliases: (null)
                    nodeid: "0"
                    nodelist: node107
                    nprocs: "1"
                    ntasks: "1"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    submit_dir: /rdma/vast-rdma/vast/fiete/jackking/cls
                    submit_host: evnode
                    task_pid: "2203433"
                    tasks_per_node: "1"
                    topology_addr: node107
                    topology_addr_pattern: node
                    working_cluster: openmind7:om-svc01:6817:9728:109
                startedAt: "2025-10-06T00:40:33.449140Z"
                writerId: mhy6u6cgxsz9hpmrqck3sx46zc7d90m4
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 16
                - 61
            "4": 3.12.11
            "5": 0.22.1
            "12": 0.22.1
            "13": linux-x86_64
batch_episodes:
    value: 128
device:
    value: cuda
encoder_dim:
    value: null
hidden_size:
    value: 128
input_addendum:
    value: null
input_size:
    value: 6
input_type:
    value: g_idx
lr:
    value: 0.001
model_class:
    value: GRU
n_epochs:
    value: 400
num_envs:
    value: 1
num_layers:
    value: 1
plot_every:
    value: 100
seed:
    value: 0
size:
    value: 10
speed:
    value: 1
steps_per_episode:
    value: 20
val_batch_episodes:
    value: 4
