_wandb:
    value:
        cli_version: 0.22.1
        e:
            subyv8bzplfqhgfkfnt9nk9uqta6kra0:
                args:
                    - --size
                    - "10"
                    - --speed
                    - "1"
                    - --n_epochs
                    - "1000"
                    - --num_envs
                    - "4"
                    - --num_val_envs
                    - "4"
                    - --batch_episodes
                    - "256"
                    - --val_batch_episodes
                    - "64"
                    - --vectorhash
                    - --input_type
                    - g_idx
                    - --use_wandb
                    - --lr
                    - "1e-3"
                    - --max_envs_per_epoch
                    - "8"
                    - --input_addendum
                    - goal
                    - --train_method
                    - ppo
                    - --ppo_clip
                    - "0.2"
                    - --ppo_vf_coef
                    - "0.5"
                    - --ppo_ent_coef
                    - "0.04"
                    - --ppo_epochs
                    - "4"
                    - --encoder_dim
                    - "128"
                    - --num_encoder_layers
                    - "2"
                    - --num_rnn_layers
                    - "1"
                    - --use_preconv_codebook
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 96
                cpu_count_logical: 192
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "75125227520"
                        used: "53657153536"
                email: jack.g.king@gmail.com
                executable: /om2/user/jackking/conda/envs/cls/bin/python
                gpu: NVIDIA A100 80GB PCIe
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-1362e537-9af2-f1d1-6b3a-565eeb99821d
                host: node114
                memory:
                    total: "1081732677632"
                os: Linux-4.18.0-372.9.1.el8.x86_64-x86_64-with-glibc2.28
                program: /rdma/vast-rdma/vast/fiete/jackking/cls/train.py
                python: CPython 3.12.11
                root: /rdma/vast-rdma/vast/fiete/jackking/cls
                slurm:
                    cluster_name: openmind7
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "2"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: evlab
                    job_cpus_per_node: "2"
                    job_gid: "102035"
                    job_gpus: "7"
                    job_id: "43909334"
                    job_name: cls
                    job_nodelist: node114
                    job_num_nodes: "1"
                    job_partition: evlab
                    job_qos: evlab
                    job_uid: "192617"
                    job_user: jackking
                    jobid: "43909334"
                    localid: "0"
                    mem_per_node: "51200"
                    nnodes: "1"
                    node_aliases: (null)
                    nodeid: "0"
                    nodelist: node114
                    nprocs: "1"
                    ntasks: "1"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    submit_dir: /rdma/vast-rdma/vast/fiete/jackking/cls
                    submit_host: evnode
                    task_pid: "3254114"
                    tasks_per_node: "1"
                    topology_addr: node114
                    topology_addr_pattern: node
                    working_cluster: openmind7:om-svc01:6817:9728:109
                startedAt: "2025-10-06T10:01:09.571784Z"
                writerId: subyv8bzplfqhgfkfnt9nk9uqta6kra0
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 16
                - 61
            "4": 3.12.11
            "5": 0.22.1
            "12": 0.22.1
            "13": linux-x86_64
batch_episodes:
    value: 256
device:
    value: cuda
encoder_dim:
    value: 128
hidden_size:
    value: 128
input_addendum:
    value: goal
input_size:
    value: 12
input_type:
    value: g_idx
lr:
    value: 0.001
max_envs_per_epoch:
    value: 8
model_class:
    value: GRU
n_epochs:
    value: 1000
num_encoder_layers:
    value: 2
num_envs:
    value: 4
num_rnn_layers:
    value: 1
num_val_envs:
    value: 4
plot_every:
    value: 100
ppo_clip:
    value: 0.2
ppo_ent_coef:
    value: 0.04
ppo_epochs:
    value: 4
ppo_vf_coef:
    value: 0.5
seed:
    value: 0
size:
    value: 10
speed:
    value: 1
steps_per_episode:
    value: 20
train_method:
    value: ppo
val_batch_episodes:
    value: 64
